### ISSUE TITLE
Blank screen after authorizing Github auth

### ISSUE THREAD

**Issue by mcljs** [ublabs/netlify-cms-oauth#1]
How can I solve this problem I did the steps I uploaded the site to github and set it in the config.yml of my site in Gatsby, this is what I put in the 0Auth of github

![Image](https://imgur.com/E9jQI9l.png)

When I try to access it appears that I accept permission in Github and then it turns white without redirecting me to the screen to edit the blog as the project does locally

![Image-2](https://imgur.com/f1DR78d.png)

**Comment by adrian-ub** [comment]
Hi @mcljs How do you have your config.yml configured?

**Comment by adrian-ub** [comment]
Cannot reproduce

Example

https://github.com/adrian-ub/test-netlify-cms

**Comment by PeterEhses** [comment]
I'll add to this discussion even though it's fairly old, since I am experiencing the same behaviour. 
I haven't been able to pin it down exactly, but the `window.opener.postMessage` call in callback seems to be blocked by some ad blockers or similar browser plugins/features. Here's a relevant discussion: https://bugs.chromium.org/p/chromium/issues/detail?id=303448

For me, switching to a blank install or guest account in my browsers works as a workaround. I'll try to look into possible fixes.

**Comment by adriandpdev** [comment]
i have the same problem, when i sign in with github, redirecto to https://netlify-cms-adrianub.vercel.app/callback?provider=github&code=xxxxxx&state=xxxxx and white screen. I have this config.

![image](https://github.com/ublabs/netlify-cms-oauth/assets/35174900/154c294c-36b2-47df-9950-c9025f6bbb5b)

And github config 

![image](https://github.com/ublabs/netlify-cms-oauth/assets/35174900/cc64eb9b-5ca7-4b61-83da-3779ecbec461)
